---
title: Sass or CSS in Add-Ons
order: 3
layout: page
---

= Packaging SCSS or CSS in an Add-On
:imagesdir: theme-addons

[.author]
Artur Signell

The add-on architecture of Vaadin enables you to easily create reusable components and share them with the world.
An add-on can be of various types: widgets, themes, server side components, etc.
While most of them contain Java code and classes, themes provide CSS and SCSS, which can be used as the application theme.
But, how should package add-ons that are not theme add-ons, but still include CSS or SCSS?
We explore the options by creating a fancy [classname]#DangerButton# component – a native button that should have a red background.

Let us first go back to basics of Vaadin themes without considering add-ons.
In a very basic case, where we have a regular application (and not an add-on) and want to create a red native button, we have the following options:

. Use a [classname]#NativeButton# with a style name and define the style in the application theme.

+
[source, Java]
----
NativeButton dangerButton = new NativeButton("Don’t click me");
dangerButton.addStyleName("danger");
----
+
In the application theme:
+
[source, CSS]
----
.danger {
   background-color: red;
}
----
+
In our application, we would of course encapsulate this in a [classname]#DangerButton# (that extends [classname]#NativeButton#) that always adds the “danger” style name.

. Use [classname]#NativeButton# with a style name and [classname]#@Stylesheet# to include the style.
+
Do as above, but create a custom CSS file which we place in the same folder as [filename]#DangerButton.java# and annotate [classname]#DangerButton# with `@Stylesheet("dangerbutton.css")` for the UI.
The [classname]#@Stylesheet# annotation will take care of publishing the CSS file and make the browser load it.

. Create a custom connector and define the style in-line.
+
Create a custom component  and a connector by creating a [classname]#DangerButton# (that extends [classname]#NativeButton#) and [classname]#DangerButtonConnector# (extends [classname]#NativeButtonConnector#).
You can then manage to do this in the connector, for example, by setting an in-line style when creating the widget.
The benefit of this is that it will work without a custom theme, while the downside is that tuning the exact red color becomes cumbersome, as you need to recompile the widget set for each update.

. Include the style sheet in a widget set.

Include the style sheet in a widget set by adding:

[subs="normal"]
----
<stylesheet src="[replaceable]##dangerbutton-widgetset.css##"/>
----

to the widget set [filename]#gwt.xml# file and adding the CSS file to the [filename]#public# folder inside the widget set folder (containing the [filename]#gwt.xml# file), so that it will be included in the compiled widget set.

. Dynamically inject the styles.
+
Use [classname]#NativeButton# with a style name and dynamically inject the CSS needed.
For example:

[source, Java]
----
NativeButton dangerButton = new NativeButton("Don’t click me");
dangerButton.addStyleName("injectedDanger");
getPage().getStyles().add(".injectedDanger {background-color: red;}");
----

This approach does not require widget set compilation or a custom theme but does not support SCSS and injecting a lot of CSS this way can quickly add up to a lot of style tags in the page.

== What About the Add-On?

Returning to add-on discussion, which of the options above are viable for an add-on?
What should we really use for our [classname]#DangerButton# add-on to keep it simple and avoid possible future problems?

The first option, which includes the application theme, is not viable for an add-on as such except if we are fine with documenting that you should copy paste the CSS into your application theme.

Option 2 seems like a good option but the day we add images or other resources to the style sheet we will run into problems as [classname]#@Stylesheet# only publishes the CSS file and nothing else.
Including other style sheets (even when they are published with [classname]#@Stylesheet# also) does not work as we do not know the actual URL they will be available from at runtime and including images will also cause issues as we have no easy way of making them available.
Also we cannot use SCSS with this approach.

Option 3 and 4 with the custom widget set usually work out fine, you can even use SCSS for these (although it will not be included in the application theme, for example, prefixed correctly). However, if we want to keep things simple we do not want to make the add-on user compile widget set.

We also do not want to go with option 5 as it does not support SCSS and have potential issues when overused, especially in older Internet Explorers.

== So, what about the add-on..?

A sometimes overlooked feature of Vaadin is the [filename]#VAADIN# folder used to serve themes and widget sets to the browser.
As a matter of fact, all files inside the [filename]#VAADIN# folder are published directly as-is to the web, also when the [filename]#VAADIN# folder is in an add-on JAR.
So, by placing our style sheet inside a “[filename]##/VAADIN/addons/dangerbutton/##” folder, it will be available for the browser and any images or related style sheets will also be available (and relative paths will work).
The only question remaining is how we can include the style sheet automatically for any user of our add-on and this can be done using the [classname]#@StyleSheet# annotation with the special `vaadin://` protocol.

For example:

[source, Java, subs="normal"]
----
@StyleSheet(“vaadin://addons/[replaceable]##dangerbutton/styles.css##”)
----

== That Does not Work with SCSS!

One of the nice features of SCSS is that the theme creator can define variables which you can use in your own scss file. If we are doing standalone compilation of the scss file to css we are not able to take advantage of these features. Also our styles will not be restricted to the application theme (using theme name prefixing) if it is not compiled at the same time as the application theme. Finally by including the styles in the application theme, all possible minifiers and similar can operate on the add-on styles also.

To take full advantage of SCSS we can, instead of using the [classname]#@Stylesheet# annotation to include a CSS file directly, define in the add-on metadata that the add-on JAR contains a SCSS (or CSS) file that should be included when compiling the application theme.
This is done with the `Vaadin-Stylesheets` attribute, for example, for our [classname]#DangerButton# as:

[source]
----
Vaadin-Stylesheets: VAADIN/addons/dangerbutton/dangerbutton.scss
----

A small gotcha here is that the `Vaadin-Stylesheet` attribute refers to the full path inside the add-on JAR (that is, it starts with `/VAADIN`), whereas the `/VAADIN` part is included in the `vaadin://` protocol when using [classname]#@Stylesheet#.

Now when you add the `dangerbutton` add-on JAR to a project, you will see that the [filename]#addons.scss# file gets automatically updated to include the `dangerbutton` CSS and it is compiled together with the rest of the application theme.
